"""Synchronous online SAC trainer initialized from privileged self-distillation."""

import os
from collections.abc import Callable
from dataclasses import dataclass, field

import torch
import torch.nn.functional as F
from trl.experimental.sdft import SDFTConfig, SDFTTrainer
from trl.models.utils import _ForwardRedirection
from trl.trainer.utils import selective_log_softmax

from .lib import (
    ResidualQHead,
    compute_soft_q_lambda_returns,
    make_soft_value_estimator,
    masked_sequence_mean,
    terminal_token_rewards,
)


Q_HEAD_FILE = "sac_q_head.pt"
SOFT_BETA = 1.0
GAMMA = 1.0
_TEACHER_SCORE_CHUNK_SIZE = 128


@dataclass
class SACConfig(SDFTConfig):
    """SDFT rollout configuration plus the deliberately small SAC surface."""

    soft_v_estimator: str = field(
        default="topk",
        metadata={"help": "Soft-V estimator: topk now, sampled SARSA in a later experiment."},
    )
    soft_v_topk: int = field(
        default=100,
        metadata={"help": "Student top-K support for the renormalized soft value."},
    )
    lam: float = field(
        default=0.0,
        metadata={"help": "Lambda for soft action-value returns; 0 is one-step TD."},
    )

    def __post_init__(self):
        super().__post_init__()
        if self.soft_v_estimator not in {"topk", "sarsa"}:
            raise ValueError(
                f"soft_v_estimator must be 'topk' or 'sarsa'; got {self.soft_v_estimator!r}"
            )
        if self.soft_v_topk < 1:
            raise ValueError(f"soft_v_topk must be >= 1; got {self.soft_v_topk}")
        if not 0.0 <= self.lam <= 1.0:
            raise ValueError(f"lam must be in [0, 1]; got {self.lam}")
        if self.teacher_model_kind != "base":
            raise ValueError("initial SAC experiments require a separate frozen base teacher")
        if self.generate_from_teacher:
            raise ValueError("SAC rollouts must be generated by the student")
        if self.num_iterations != 1:
            raise ValueError("online SAC requires num_iterations=1 (one update per rollout batch)")
        if self.temperature != 1.0 or self.top_p != 1.0 or self.top_k != 0 or self.min_p is not None:
            raise ValueError(
                "SAC currently requires untruncated temperature-1 sampling: "
                "temperature=1, top_p=1, top_k=0, min_p=None"
            )
        if self.repetition_penalty != 1.0:
            raise ValueError("SAC currently requires repetition_penalty=1")
        if self.generation_kwargs is not None:
            raise ValueError("generation_kwargs are disabled so rollout and scored policies cannot diverge")
        if self.num_loss_tokens_to_skip != 0:
            raise ValueError("SAC trains every completion token; num_loss_tokens_to_skip must be 0")
        if self.use_teacher_server:
            raise ValueError("SAC needs local privileged-teacher hidden states")
        if self.use_liger_kernel:
            raise ValueError("the initial SAC loss does not use the SDFT Liger divergence kernel")


class SACTrainer(SDFTTrainer):
    """SDFT rollout machinery with a frozen-teacher residual Q and soft actor loss."""

    _name = "SAC"
    _tag_names = ["trl", "sdft", "sac"]
    config_cls = SACConfig

    def __init__(
        self,
        *args,
        reward_func: Callable[..., list[float | None]],
        **kwargs,
    ):
        self.reward_func = reward_func
        super().__init__(*args, **kwargs)

        self.soft_value_estimator = make_soft_value_estimator(
            self.args.soft_v_estimator, topk=self.args.soft_v_topk
        )
        teacher = self.accelerator.unwrap_model(self.teacher_model)
        hidden_size = int(teacher.config.hidden_size)
        # Keep the small critic head in fp32; autocast handles its matmuls against
        # bf16 teacher activations while the optimizer retains fp32 parameters.
        q_head = ResidualQHead(hidden_size).to(device=self.accelerator.device)
        self.q_head = self.accelerator.prepare_model(q_head)
        self.q_head.train()
        self._sac_forward_redirection = _ForwardRedirection()

    # -- dataset and online reward -----------------------------------------

    def _set_signature_columns_if_needed(self):
        if self._signature_columns is None:
            self._signature_columns = ["prompt", "privileged_context", "solution"]

    def _prepare_training_batch(self, inputs):
        batch = super()._prepare_training_batch(inputs)
        completion_ids_list = self._get_completion_ids_list(batch)
        completion_texts = self._tokenizer.batch_decode(
            completion_ids_list, skip_special_tokens=True
        )
        completions = [
            [{"role": "assistant", "content": text}] for text in completion_texts
        ]
        solutions = [example["solution"] for example in inputs]
        rewards = self.reward_func(completions=completions, solution=solutions)
        if len(rewards) != batch["completion_ids"].size(0):
            raise RuntimeError(
                f"reward function returned {len(rewards)} values for "
                f"{batch['completion_ids'].size(0)} rollouts"
            )

        device = self.accelerator.device
        reward_tensor = torch.tensor(
            [float("nan") if reward is None else float(reward) for reward in rewards],
            device=device,
            dtype=torch.float32,
        )
        scorable = torch.isfinite(reward_tensor)
        batch["terminal_rewards"] = torch.nan_to_num(reward_tensor, nan=0.0)
        batch["scorable"] = scorable.float()

        mode = "train" if self.model.training else "eval"
        gathered_rewards = self.accelerator.gather(batch["terminal_rewards"])
        gathered_scorable = self.accelerator.gather(batch["scorable"])
        reward_mean = (gathered_rewards * gathered_scorable).sum() / gathered_scorable.sum().clamp(min=1.0)
        self._metrics[mode]["sac/reward_mean"].append(reward_mean.item())
        self._metrics[mode]["sac/unscorable_rate"].append(
            (1.0 - gathered_scorable.mean()).item()
        )
        return batch

    # -- residual-Q optimizer ownership ------------------------------------

    def create_optimizer(self, *args, **kwargs):
        optimizer = super().create_optimizer(*args, **kwargs)
        existing = {id(parameter) for group in optimizer.param_groups for parameter in group["params"]}
        q_parameters = [
            parameter
            for parameter in self.q_head.parameters()
            if parameter.requires_grad and id(parameter) not in existing
        ]
        if q_parameters:
            optimizer.add_param_group({"params": q_parameters})
        return optimizer

    def _clip_grad_norm(self, model):
        policy_norm = super()._clip_grad_norm(model)
        parameters = [parameter for parameter in self.q_head.parameters() if parameter.grad is not None]
        if parameters:
            limit = self.args.max_grad_norm
            q_norm = torch.nn.utils.clip_grad_norm_(
                parameters, limit if limit and limit > 0 else float("inf")
            )
            mode = "train" if self.model.training else "eval"
            self._metrics[mode]["sac/q_grad_norm"].append(q_norm.item())
        return policy_norm

    # -- frozen privileged teacher -----------------------------------------

    def _teacher_scores_and_q_inputs(self, inputs, topk_ids):
        teacher = self.accelerator.unwrap_model(self.teacher_model)
        with torch.no_grad(), self._get_teacher_context_for_self_distillation():
            return self._sac_forward_redirection(
                self.teacher_model,
                teacher,
                self._teacher_score_side,
                teacher,
                inputs,
                topk_ids,
            )

    def _teacher_score_side(self, teacher, inputs, topk_ids):
        completion_ids = inputs["completion_ids"]
        logits_to_keep = completion_ids.size(1)
        hidden = teacher.get_decoder()(
            input_ids=inputs["teacher_input_ids"],
            attention_mask=inputs["teacher_attention_mask"],
            use_cache=False,
        ).last_hidden_state
        hidden = hidden[:, :-1][:, -logits_to_keep:]

        head = teacher.get_output_embeddings()
        sampled_action_vectors = F.embedding(completion_ids, head.weight).detach().clone()
        sampled_teacher_logps = []
        topk_teacher_logps = []
        topk_corrections = []

        for start in range(0, logits_to_keep, _TEACHER_SCORE_CHUNK_SIZE):
            stop = min(start + _TEACHER_SCORE_CHUNK_SIZE, logits_to_keep)
            chunk_hidden = hidden[:, start:stop]
            chunk_sampled_ids = completion_ids[:, start:stop]
            chunk_topk_ids = topk_ids[:, start:stop]
            selected_ids = torch.cat(
                [chunk_sampled_ids.unsqueeze(-1), chunk_topk_ids], dim=-1
            )

            teacher_logits = F.linear(chunk_hidden, head.weight, head.bias) / self.temperature
            selected_teacher_logps = selective_log_softmax(teacher_logits, selected_ids)
            sampled_teacher_logps.append(selected_teacher_logps[..., 0].float())
            topk_teacher_logps.append(selected_teacher_logps[..., 1:].float())
            del teacher_logits, selected_teacher_logps

            residual_hidden = self.q_head(chunk_hidden)
            correction_logits = F.linear(residual_hidden.float(), head.weight.float(), None)
            topk_corrections.append(
                torch.gather(correction_logits, dim=-1, index=chunk_topk_ids).float()
            )

        return {
            "hidden": hidden.detach(),
            "sampled_action_vectors": sampled_action_vectors,
            "sampled_teacher_logps": torch.cat(sampled_teacher_logps, dim=1),
            "topk_teacher_logps": torch.cat(topk_teacher_logps, dim=1),
            "topk_corrections": torch.cat(topk_corrections, dim=1),
        }

    # -- synchronous actor and critic loss ---------------------------------

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        if return_outputs:
            raise ValueError("SACTrainer does not support returning model outputs")
        self.q_head.train(model.training)

        completion_ids = inputs["completion_ids"]
        completion_mask = inputs["completion_mask"].float()
        student_input_ids = torch.cat([inputs["prompt_ids"], completion_ids], dim=1)
        student_attention_mask = torch.cat(
            [inputs["prompt_mask"], inputs["completion_mask"]], dim=1
        )
        student_logits = self._forward_logits(
            model,
            student_input_ids,
            student_attention_mask,
            completion_ids.size(1),
        )

        topk_ids = self.soft_value_estimator.select_token_ids(student_logits)
        selected_ids = torch.cat([completion_ids.unsqueeze(-1), topk_ids], dim=-1)
        selected_student_logps = selective_log_softmax(student_logits, selected_ids)
        sampled_student_logps = selected_student_logps[..., 0]
        topk_student_logps = selected_student_logps[..., 1:].detach()

        teacher = self._teacher_scores_and_q_inputs(inputs, topk_ids)
        residual_hidden = self.q_head(teacher["hidden"])
        sampled_correction = (
            residual_hidden.float() * teacher["sampled_action_vectors"].float()
        ).sum(dim=-1)
        sampled_q = teacher["sampled_teacher_logps"] + sampled_correction

        support = self.soft_value_estimator.build_support(topk_ids, topk_student_logps)
        topk_q = teacher["topk_teacher_logps"] + teacher["topk_corrections"]
        soft_values = self.soft_value_estimator.estimate(topk_q, support)

        with torch.no_grad():
            soft_advantages = (
                sampled_q.detach() - sampled_student_logps.detach() - soft_values
            )
            token_rewards = terminal_token_rewards(
                inputs["terminal_rewards"].float(), completion_mask
            )
            q_targets = compute_soft_q_lambda_returns(
                token_rewards,
                soft_values,
                sampled_student_logps.detach(),
                completion_mask,
                lam=self.args.lam,
                gamma=GAMMA,
            )

        loss_mask = completion_mask * inputs["scorable"].float().unsqueeze(1)
        actor_loss = masked_sequence_mean(
            -sampled_student_logps * soft_advantages, loss_mask
        )
        q_loss = masked_sequence_mean((sampled_q - q_targets) ** 2, loss_mask)
        loss = actor_loss + q_loss

        mode = "train" if model.training else "eval"
        self._record_sac_metrics(
            mode,
            actor_loss=actor_loss,
            q_loss=q_loss,
            sampled_q=sampled_q,
            sampled_correction=sampled_correction,
            soft_values=soft_values,
            soft_advantages=soft_advantages,
            q_targets=q_targets,
            topk_mass=support.mass,
            mask=loss_mask,
        )

        accumulation_scale = self.current_gradient_accumulation_steps if model.training else 1.0
        return loss / accumulation_scale

    @staticmethod
    def _masked_token_mean(values, mask):
        values = values.float()
        mask = mask.float()
        return (values * mask).sum() / mask.sum().clamp(min=1.0)

    def _record_sac_metrics(self, mode, *, mask, **metrics):
        loss_names = {"actor_loss", "q_loss"}
        for name, value in metrics.items():
            if name not in loss_names:
                value = self._masked_token_mean(value, mask)
            gathered = self.accelerator.gather(value.detach()).mean().item()
            self._metrics[mode][f"sac/{name}"].append(gathered)

    # -- Q-head checkpointing ----------------------------------------------

    def _save_q_head(self, output_dir):
        if not self.args.should_save:
            return
        q_head = self.accelerator.unwrap_model(self.q_head)
        torch.save(q_head.state_dict(), os.path.join(output_dir, Q_HEAD_FILE))

    def save_model(self, output_dir=None, _internal_call=False):
        output_dir = output_dir or self.args.output_dir
        super().save_model(output_dir, _internal_call=_internal_call)
        self._save_q_head(output_dir)

    def _load_from_checkpoint(self, resume_from_checkpoint, model=None):
        super()._load_from_checkpoint(resume_from_checkpoint, model)
        path = os.path.join(resume_from_checkpoint, Q_HEAD_FILE)
        if not os.path.isfile(path):
            raise FileNotFoundError(
                f"No SAC Q-head weights ({Q_HEAD_FILE}) found in {resume_from_checkpoint}"
            )
        state = torch.load(path, map_location="cpu", weights_only=True)
        self.accelerator.unwrap_model(self.q_head).load_state_dict(state)
        print(f"Restored SAC Q head <- {path}")

    def _maybe_log_save_evaluate(self, *args, **kwargs):
        self.q_head.zero_grad(set_to_none=True)
        return super()._maybe_log_save_evaluate(*args, **kwargs)
