"""Dataset and reward machinery for the first learned-hint experiment.

The trainable policy reads ``(problem, worked solution)`` and emits a short hint. A
frozen copy of the original policy then supplies the two expensive reward terms:

* sufficiency: fraction of verified-correct solutions sampled under the hint;
* transfer: sampled-token reverse KL on frozen-student rollouts.

The frozen model is loaded lazily. In colocated vLLM mode, TRL calls the reward only
after its generation engine has entered level-2 sleep, leaving room for the teacher.
"""

from __future__ import annotations

import hashlib
import os
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

import torch
from datasets import Dataset, load_from_disk

from train.opsd.train_sdft import PI_HINT
from train.opsd.train_self_teacher.lib import per_token_logps, rollout_path
from utils import compose_pi_messages, format_prompt_math, grade, load_train_dataset
from utils.gen_hints import build_messages, leaks_answer

HINT_GEN_VERSION = "composite_sct_v1"


def _as_rows(dataset: Iterable[dict]) -> list[dict]:
    return [dict(row) for row in dataset]


def group_student_rollouts(
    rollouts: Iterable[dict],
    model: str,
    dataset: str,
) -> dict[str, list[dict]]:
    """Validate and group a frozen-student rollout cache by question."""
    rows = _as_rows(rollouts)
    if not rows:
        raise ValueError("The student rollout cache is empty.")

    required = {"question", "completion_ids", "gen_model", "dataset"}
    missing = required.difference(rows[0])
    if missing:
        raise ValueError(f"Student rollout cache is missing columns {sorted(missing)}")
    gen_models = {row["gen_model"] for row in rows}
    datasets = {row["dataset"] for row in rows}
    if gen_models != {model}:
        raise ValueError(f"Student rollouts were generated by {gen_models}, not {model!r}.")
    if datasets != {dataset}:
        raise ValueError(f"Student rollouts are for {datasets}, not {dataset!r}.")

    grouped: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        grouped[str(row["question"])].append(row)
    for question_rows in grouped.values():
        question_rows.sort(
            key=lambda row: (
                int(row.get("sample_idx", 0)),
                str(row.get("rollout_id", "")),
            )
        )
    return dict(grouped)


def index_student_rollouts(
    rollouts: Dataset,
    model: str,
    dataset: str,
) -> dict[str, list[int]]:
    """Index Arrow rows by question without materializing long token columns."""
    required = {"question", "completion_ids", "gen_model", "dataset"}
    missing = required.difference(rollouts.column_names)
    if missing:
        raise ValueError(f"Student rollout cache is missing columns {sorted(missing)}")
    gen_models = set(rollouts.unique("gen_model"))
    datasets = set(rollouts.unique("dataset"))
    if gen_models != {model}:
        raise ValueError(f"Student rollouts were generated by {gen_models}, not {model!r}.")
    if datasets != {dataset}:
        raise ValueError(f"Student rollouts are for {datasets}, not {dataset!r}.")

    questions = rollouts["question"]
    sample_indices = (
        rollouts["sample_idx"]
        if "sample_idx" in rollouts.column_names
        else [0] * len(rollouts)
    )
    rollout_ids = (
        rollouts["rollout_id"]
        if "rollout_id" in rollouts.column_names
        else [""] * len(rollouts)
    )
    grouped: dict[str, list[int]] = defaultdict(list)
    for row_idx, question in enumerate(questions):
        grouped[str(question)].append(row_idx)
    for row_indices in grouped.values():
        row_indices.sort(key=lambda i: (int(sample_indices[i]), str(rollout_ids[i])))
    return dict(grouped)


def build_hint_grpo_dataset(
    model: str,
    dataset: str,
    tokenizer,
    rollout_root: str = "data/rollouts",
    transfer_rollouts: int = 4,
    max_samples: int | None = None,
    max_model_length: int = 32768,
    hint_budget: int = 128,
    mixed_only: bool = False,
) -> Dataset:
    """Build one generator prompt per question with enough student rollouts.

    The worked solution is visible only in the generator prompt. Reward-time teacher
    prompts are rebuilt from ``question`` and the sampled hint, so the demonstration
    never reaches the hinted teacher.
    """
    if transfer_rollouts < 1:
        raise ValueError("transfer_rollouts must be >= 1")
    if hint_budget < 1:
        raise ValueError("hint_budget must be >= 1")
    if max_model_length <= hint_budget:
        raise ValueError("max_model_length must exceed hint_budget")

    cache_path = rollout_path(model, dataset, rollout_root)
    if not os.path.isdir(cache_path):
        raise FileNotFoundError(
            f"No frozen-student rollout cache at {cache_path}. Generate it first with:\n"
            "  python -m train.opsd.train_self_teacher.gen_rollouts "
            f"--model {model} --dataset {dataset} --n {transfer_rollouts}"
        )
    rollouts = load_from_disk(cache_path)
    grouped = index_student_rollouts(rollouts, model, dataset)
    rollout_rewards = rollouts["reward"] if "reward" in rollouts.column_names else None

    source = load_train_dataset(dataset, require_solution=True)
    rows = []
    skipped_rollouts = skipped_outcomes = skipped_length = 0
    prompt_budget = max_model_length - hint_budget
    for row in source:
        question = str(row["question"])
        question_rollout_indices = grouped.get(question, [])
        if len(question_rollout_indices) < transfer_rollouts:
            skipped_rollouts += 1
            continue
        selected = question_rollout_indices[:transfer_rollouts]
        if mixed_only:
            if rollout_rewards is None:
                raise ValueError("--mixed-only needs a rollout cache with verifier rewards.")
            successes = sum(float(rollout_rewards[i]) > 0.5 for i in selected)
            if successes in (0, len(selected)):
                skipped_outcomes += 1
                continue

        prompt = build_messages(question, str(row["solution"]))
        encoded = tokenizer.apply_chat_template(
            [prompt],
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            enable_thinking=False,
        )["input_ids"][0]
        if len(encoded) > prompt_budget:
            skipped_length += 1
            continue
        rows.append(
            {
                "prompt": prompt,
                "question": question,
                "final_answer": str(row["final_answer"]),
            }
        )
        if max_samples is not None and len(rows) >= max_samples:
            break

    if not rows:
        raise RuntimeError("No questions survived hint-generator dataset construction.")
    print(
        f"Built {len(rows)} hint-generator questions from {cache_path} "
        f"(skipped: {skipped_rollouts} insufficient rollouts, "
        f"{skipped_outcomes} non-mixed, {skipped_length} overlong prompts)"
    )
    return Dataset.from_list(rows)


def completion_text(completion: Any) -> str:
    """Extract assistant text from TRL's conversational or plain completion shape."""
    if isinstance(completion, str):
        return completion.strip()
    if isinstance(completion, dict):
        return str(completion.get("content", "")).strip()
    if isinstance(completion, list):
        for message in reversed(completion):
            if isinstance(message, dict) and message.get("role") == "assistant":
                return str(message.get("content", "")).strip()
        if completion:
            return completion_text(completion[-1])
    return ""


def invalid_hint_reason(hint: str, final_answer: str) -> str | None:
    """Return why a sampled hint is inadmissible, or ``None`` when usable."""
    if not hint:
        return "empty"
    if "<think>" in hint or "</think>" in hint:
        # Thinking is disabled in the generator template. Reject it if the model
        # nevertheless opens the hidden channel: otherwise it receives uncharged tokens.
        return "thinking"
    if leaks_answer(hint, final_answer):
        return "answer_leak"
    return None


def normalized_hint_cost(completion_ids: list[int], hint_budget: int) -> float:
    """Realized generated-token cost, normalized to [0, 1] by the hard budget."""
    if hint_budget < 1:
        raise ValueError("hint_budget must be >= 1")
    return min(len(completion_ids) / hint_budget, 1.0)


def sampled_reverse_kl(
    student_logps: torch.Tensor,
    hinted_teacher_logps: torch.Tensor,
    clamp_nonnegative: bool = True,
) -> float:
    """Mean sampled estimate of KL(student || hinted teacher), in nats/token."""
    if student_logps.shape != hinted_teacher_logps.shape:
        raise ValueError("student and teacher log-probabilities must have the same shape")
    if student_logps.numel() == 0:
        raise ValueError("cannot estimate transfer cost from an empty completion")
    estimate = (student_logps.float() - hinted_teacher_logps.float()).mean().item()
    return max(0.0, estimate) if clamp_nonnegative else estimate


def composite_reward(
    sufficiency: float,
    hint_cost: float,
    transfer_cost: float,
    alpha: float,
    gamma: float,
) -> float:
    return alpha * sufficiency - hint_cost - gamma * transfer_cost


@dataclass(frozen=True)
class HintRewardConfig:
    model: str
    dataset: str
    rollout_root: str = "data/rollouts"
    hint_budget: int = 128
    teacher_rollouts: int = 2
    transfer_rollouts: int = 4
    teacher_max_completion_length: int = 4096
    teacher_temperature: float = 1.0
    teacher_top_p: float = 1.0
    alpha: float = 1.0
    gamma: float = 1.0
    invalid_penalty: float = 1.0
    recompute_student_logps: bool = True
    clamp_transfer: bool = True

    def validate(self) -> None:
        if self.hint_budget < 1:
            raise ValueError("hint_budget must be >= 1")
        if self.teacher_rollouts < 1 or self.transfer_rollouts < 1:
            raise ValueError("teacher_rollouts and transfer_rollouts must be >= 1")
        if self.teacher_temperature <= 0:
            raise ValueError("teacher_temperature must be > 0 for stochastic reliability rollouts")
        if not 0 < self.teacher_top_p <= 1:
            raise ValueError("teacher_top_p must be in (0, 1]")
        if self.alpha < 0 or self.gamma < 0 or self.invalid_penalty < 0:
            raise ValueError("alpha, gamma, and invalid_penalty must be nonnegative")


class FrozenHintTeacher:
    """Lazy single-GPU backend for sufficiency and sampled reverse-KL scoring."""

    def __init__(self, config: HintRewardConfig, tokenizer):
        config.validate()
        self.config = config
        self.tokenizer = tokenizer
        cache_path = rollout_path(config.model, config.dataset, config.rollout_root)
        if not os.path.isdir(cache_path):
            raise FileNotFoundError(f"No frozen-student rollout cache at {cache_path}")
        rollout_dataset = load_from_disk(cache_path)
        needed_columns = [
            "question",
            "completion_ids",
            "gen_model",
            "dataset",
        ]
        for optional in ("sample_idx", "rollout_id"):
            if optional in rollout_dataset.column_names:
                needed_columns.append(optional)
        if not config.recompute_student_logps:
            if "student_logps" not in rollout_dataset.column_names:
                raise ValueError("The rollout cache has no student_logps.")
            needed_columns.append("student_logps")
        self.rollout_dataset = rollout_dataset.select_columns(needed_columns)
        self.rollout_indices = index_student_rollouts(
            self.rollout_dataset, config.model, config.dataset
        )
        self.model = None
        # Recomputed unhinted logps are stable while the teacher stays frozen. Keeping
        # them on CPU avoids both repeat forwards within a GRPO group and GPU growth.
        self._student_logps: dict[str, torch.Tensor] = {}

    def _ensure_model(self):
        if self.model is not None:
            return self.model
        from transformers import AutoModelForCausalLM

        print(f"Loading frozen hint teacher {self.config.model} on cuda")
        self.model = AutoModelForCausalLM.from_pretrained(
            self.config.model,
            dtype=torch.bfloat16,
            trust_remote_code=True,
        ).eval().to("cuda")
        for parameter in self.model.parameters():
            parameter.requires_grad_(False)
        return self.model

    def _render_prompt(self, messages: list[dict]) -> list[int]:
        return self.tokenizer.apply_chat_template(
            [messages],
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
        )["input_ids"][0]

    def _hinted_messages(self, question: str, hint: str) -> list[dict]:
        context = PI_HINT.format(hint=hint)
        return compose_pi_messages(format_prompt_math(question), context)

    def score_sufficiency(self, question: str, final_answer: str, hint: str) -> float:
        model = self._ensure_model()
        prompt_ids = torch.tensor(
            self._render_prompt(self._hinted_messages(question, hint)),
            dtype=torch.long,
            device=model.device,
        ).unsqueeze(0)
        input_ids = prompt_ids.repeat(self.config.teacher_rollouts, 1)
        attention_mask = torch.ones_like(input_ids)
        generation_kwargs = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "do_sample": True,
            "temperature": self.config.teacher_temperature,
            "top_p": self.config.teacher_top_p,
            "max_new_tokens": self.config.teacher_max_completion_length,
            "pad_token_id": (
                self.tokenizer.pad_token_id or self.tokenizer.eos_token_id
            ),
            "eos_token_id": self.tokenizer.eos_token_id,
            "use_cache": True,
        }
        with torch.inference_mode():
            output_ids = model.generate(**generation_kwargs)
        prompt_length = input_ids.size(1)
        solutions = self.tokenizer.batch_decode(
            output_ids[:, prompt_length:], skip_special_tokens=True
        )
        correct = [grade(solution, final_answer)[1] for solution in solutions]
        return sum(correct) / len(correct)

    @staticmethod
    def _rollout_key(question: str, rollout: dict) -> str:
        if rollout.get("rollout_id"):
            return str(rollout["rollout_id"])
        payload = (
            question
            + "\0"
            + str(rollout.get("sample_idx", 0))
            + "\0"
            + ",".join(map(str, rollout["completion_ids"]))
        )
        return hashlib.sha256(payload.encode()).hexdigest()[:24]

    def _score_tokens(self, prompt_ids: list[int], completion_ids: list[int]) -> torch.Tensor:
        model = self._ensure_model()
        completion = torch.tensor(
            completion_ids, dtype=torch.long, device=model.device
        ).unsqueeze(0)
        prompt = torch.tensor(prompt_ids, dtype=torch.long, device=model.device).unsqueeze(0)
        input_ids = torch.cat([prompt, completion], dim=1)
        with torch.inference_mode():
            logps = per_token_logps(model, input_ids, completion).squeeze(0).cpu()
        return logps

    def score_transfer(self, question: str, hint: str) -> float:
        question_rollout_indices = self.rollout_indices.get(question, [])
        if len(question_rollout_indices) < self.config.transfer_rollouts:
            raise ValueError(
                f"Question has {len(question_rollout_indices)} cached rollouts, but "
                f"transfer_rollouts={self.config.transfer_rollouts}."
            )
        base_prompt_ids = self._render_prompt(format_prompt_math(question))
        hinted_prompt_ids = self._render_prompt(self._hinted_messages(question, hint))
        estimates = []
        for rollout_idx in question_rollout_indices[: self.config.transfer_rollouts]:
            rollout = self.rollout_dataset[rollout_idx]
            completion_ids = list(rollout["completion_ids"])
            key = self._rollout_key(question, rollout)
            if self.config.recompute_student_logps:
                if key not in self._student_logps:
                    self._student_logps[key] = self._score_tokens(
                        base_prompt_ids, completion_ids
                    )
                student_logps = self._student_logps[key]
            else:
                if "student_logps" not in rollout:
                    raise ValueError(
                        "The rollout cache has no student_logps; either regenerate it or use "
                        "--recompute-student-logps."
                    )
                student_logps = torch.tensor(rollout["student_logps"], dtype=torch.float32)
            teacher_logps = self._score_tokens(hinted_prompt_ids, completion_ids)
            estimates.append(
                sampled_reverse_kl(
                    student_logps,
                    teacher_logps,
                    clamp_nonnegative=False,
                )
            )
        estimate = sum(estimates) / len(estimates)
        return max(0.0, estimate) if self.config.clamp_transfer else estimate


class CompositeHintReward:
    """TRL-compatible composite reward with explicit component logging."""

    def __init__(self, config: HintRewardConfig, backend: FrozenHintTeacher):
        config.validate()
        self.config = config
        self.backend = backend

    def __call__(
        self,
        prompts,
        completions,
        completion_ids,
        question,
        final_answer,
        log_extra=None,
        log_metric=None,
        **_,
    ) -> list[float]:
        del prompts  # all reward prompts are reconstructed from the raw question
        rewards, successes, costs, transfers, invalids = [], [], [], [], []
        reasons = []
        for completion, token_ids, q, answer in zip(
            completions, completion_ids, question, final_answer, strict=True
        ):
            hint = completion_text(completion)
            cost = normalized_hint_cost(token_ids, self.config.hint_budget)
            reason = invalid_hint_reason(hint, str(answer))
            if reason is not None:
                success, transfer = 0.0, 0.0
                reward = -self.config.invalid_penalty - cost
                invalid = 1.0
            else:
                success = self.backend.score_sufficiency(str(q), str(answer), hint)
                transfer = self.backend.score_transfer(str(q), hint)
                reward = composite_reward(
                    success,
                    cost,
                    transfer,
                    self.config.alpha,
                    self.config.gamma,
                )
                invalid = 0.0
                reason = ""
            rewards.append(float(reward))
            successes.append(float(success))
            costs.append(float(cost))
            transfers.append(float(transfer))
            invalids.append(invalid)
            reasons.append(reason)

        if log_extra is not None:
            log_extra("hint_sufficiency", successes)
            log_extra("hint_cost", costs)
            log_extra("hint_transfer", transfers)
            log_extra("hint_invalid_reason", reasons)
        if log_metric is not None:
            log_metric("hint/sufficiency", sum(successes) / len(successes))
            log_metric("hint/cost", sum(costs) / len(costs))
            log_metric("hint/transfer", sum(transfers) / len(transfers))
            log_metric("hint/invalid_fraction", sum(invalids) / len(invalids))
        return rewards


def make_reward_function(config: HintRewardConfig, tokenizer):
    """Create a named closure because GRPOTrainer expects ``reward_func.__name__``."""
    backend = FrozenHintTeacher(config, tokenizer)
    reward = CompositeHintReward(config, backend)

    def hint_composite_reward(**kwargs):
        return reward(**kwargs)

    return hint_composite_reward
